### ISSUE TITLE
Week9 readyto review

### ISSUE THREAD

**Issue by skotcharat** [mad-java-ent-f20/MoodyBooze#1]
@pawaitemadisoncollege Week 9 work ready to review

**Comment by pawaitemadisoncollege** [comment]
The idea here is that if you have three different response formats (@produces) https://github.com/mad-java-ent-f20/MoodyBooze/blob/275ce2ca0f7bd86093640fb9cfd9c87dec5ab067/src/main/java/api/HelloWorld.java#L15, you will have three methods. Each one will return a different format:


       @GET
       @Produces("text/plain")
	public String doGetText() {
		...
	}

	@GET
	@Produces("text/html")
	public String doGetHtml() {
		...
        etc.


You might list multiple types in `@produces` to handle something like:` @Produces({"image/jpeg,image/png"})`

**Comment by skotcharat** [comment]
@pawaitemadisoncollege week9 ready to review

**Comment by pawaitemadisoncollege** [comment]
Week 9 looks good now! Thanks!

**Comment by skotcharat** [comment]
@pawaitemadisoncollege Thank you
